name        : Tor's Jekyll Blog
brand       : The Tortoro
description : Tor's Site
keyword     :
url         : torleif-nielsen.github.io
email       : torleif@hawaii.edu
twitter     :
github      : torleif-nielsen
author      : Torleif Nielsen
analytics   : UA-8418273-8
year        : 2016
markdown : kramdown
exclude :
  - node_modules
