name : Foundation5/github pages/Jykill starter
brand : My Site
description : This is the description of my site
keyword : 
url : http://daigofuji.github.io/jekyll-foundation-6-starter/
email : daigo@daigofujiwara.com
twitter : DaigoFuji
github : DaigoFuji
author : Daigo Fujiwara
analytics : UA-8418273-8
year : 2016
markdown : kramdown
exclude :
  - node_modules
